version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql8.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beango  # 可选：初始创建数据库
      TZ: Asia/Shanghai       # 时区设置
    ports:
      - "3306:3306"
    volumes:
      # - /Users/jhonhe/Public/db:/var/lib/mysql 
      # WSL2 专用路径格式（需先创建目录）
      - /mnt/c/Users/Hiyashiki/Abandon/Tools/db:/var/lib/mysql
    command: 
      - --default-authentication-plugins=mysql_native_password

volumes:
  mysql_data:
    driver: local

version: '3.8'