version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql8.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root  # 设置 root 用户的密码为 root
    ports:
      - "3306:3306"
    volumes:
      - /Users/jhonhe/Public/db:/var/lib/mysql 
    command: --default-authentication-plugins=mysql_native_password

volumes:
  mysql_data:
    driver: local

